version: '3.8'

services:
  frontend:
    image: tiritibambix/dockal-frontend:latest
    ports:
      - "5182:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://<HOST_IP>:3002
    networks:
      - dockal

  backend:
    image: tiritibambix/dockal-backend:latest
    ports:
      - "3002:3000"
    depends_on:
      - radicale
    environment:
      - RADICALE_URL=http://radicale:5232
      - RADICALE_USERNAME=<RADICALE_USERNAME>
      - RADICALE_PASSWORD=<RADICALE_PASSWORD>
      - JWT_SECRET=<JWT_SECRET_KEY>
      - NODE_ENV=production
      - FRONTEND_URL=http://<HOST_IP>:5182
    networks:
      - dockal

  radicale:
    image: tomsquest/docker-radicale:latest
    ports:
      - "5232:5232"
    volumes:
      - <LOCAL_DATA_PATH>/radicale_data:/data
    environment:
      - RADICALE_STORAGE_FILESYSTEM_FOLDER=/data
    networks:
      - dockal

networks:
  dockal:
    driver: bridge

volumes:
  radicale_data:
